### PR TITLE
Minor fixes to Zigbee friendly names

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Bug fixes and fixed ordering of attributes when `SetOption83 1`.

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works on core 2.6.1
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by arendst** [comment]
I think you deleted one line too much:
```
error: 'ZIGBEE_STATUS_DEVICE_INDICATION' was not declared in this scope 
```
I'll restore file xdrv_23_zigbee_7_statemachine.ino
