### PR TITLE
Fix start_root_basic_commissioning

### LINKED ISSUE #21890: [Matter] 'attribute_error' the 'Matter_Device' object has no attribute 'start_root_basic_commissioning'
### PROBLEM DESCRIPTION

I am facing an error when trying to open Matter commissioning. Do you kwon how to fix this issue with Tasmota 14.1.0.4 (010ca34-tasmota32) ?

Exception:
`'attribute_error' the 'Matter_Device' object has no attribute 'start_root_basic_commissioning'
`

### REQUESTED INFORMATION
_Make sure your have performed every step and checked the applicable boxes before submitting your issue. Thank you!_

- [x] Read the [Contributing Guide and Policy](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md) and [the Code of Conduct](https://github.com/arendst/Tasmota/blob/development/CODE_OF_CONDUCT.md)
- [x] Searched the problem in [issues](https://github.com/arendst/Tasmota/issues)
- [x] Searched the problem in [discussions](https://github.com/arendst/Tasmota/discussions)
- [x] Searched the problem in the [docs](https://tasmota.github.io/docs/FAQ)
- [x] Searched the problem in the [chat](https://discord.gg/Ks2Kzd4)
- [x] Device used (e.g., Sonoff Basic): SparkFun Qwiic Dev Board ESP32-C6
- [x] Tasmota binary firmware version number used:14.1.0.4 (010ca34-tasmota32
  - [x] Pre-compiled
  - [ ] Self-compiled
- [x] Flashing tools used: web installer
- [x] Provide the output of command: `Backlog Template; Module; GPIO 255`:
```lua
  Configuration output here:
12:01:15.354 CMD: Grp 0, Cmd 'BACKLOG', Idx 1, Len 26, Pld -99, Data 'Template; Module; GPIO 255'
12:01:15.367 SRC: Backlog
12:01:15.367 CMD: Grp 0, Cmd 'TEMPLATE', Idx 1, Len 0, Pld -99, Data ''
12:01:15.371 MQT: stat/tasmota_482438/RESULT = {"NAME":"ESP32C6","GPIO":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0],"FLAG":0,"BASE":1}
12:01:15.600 SRC: Backlog
12:01:15.601 CMD: Grp 0, Cmd 'MODULE', Idx 1, Len 0, Pld -99, Data ''
12:01:15.604 MQT: stat/tasmota_482438/RESULT = {"Module":{"1":"ESP32C6"}}
12:01:15.804 SRC: Backlog
12:01:15.804 CMD: Grp 0, Cmd 'GPIO', Idx 1, Len 3, Pld 255, Data '255'
12:01:15.810 MQT: stat/tasmota_482438/RESULT = {"GPIO0":{"0":"None"},"GPIO1":{"0":"None"},"GPIO2":{"0":"None"},"GPIO3":{"0":"None"},"GPIO4":{"0":"None"},"GPIO5":{"0":"None"},"GPIO6":{"0":"None"},"GPIO7":{"0":"None"},"GPIO8":{"0":"None"},"GPIO9":{"0":"None"},"GPIO10":{"0":"None"},"GPIO11":{"0":"None"},"GPIO12":{"0":"None"},"GPIO13":{"0":"None"},"GPIO14":{"0":"None"},"GPIO15":{"0":"None"},"GPIO16":{"0":"None"},"GPIO17":{"0":"None"},"GPIO18":{"0":"None"},"GPIO19":{"0":"None"},"GPIO20":{"0":"None"},"GPIO21":{"0":"None"},"GPIO22":{"0":"None"},"GPIO23":{"0":"None"},"GPIO26":{"0":"None"},"GPIO28":{"0":"None"}}

```
- [ ] If using rules, provide the output of this command: `Backlog Rule1; Rule2; Rule3`:
```lua
  Rules output here:


```
- [x] Provide the output of this command: `Status 0`:
```lua
  STATUS 0 output here:
12:04:03.033 CMD: Grp 0, Cmd 'STATUS', Idx 1, Len 1, Pld 0, Data '0'
12:04:03.036 MQT: stat/tasmota_482438/STATUS = {"Status":{"Module":1,"DeviceName":"Sparkfun C6","FriendlyName":["Tasmota"],"Topic":"tasmota_482438","ButtonTopic":"0","Power":"0","PowerLock":"0","PowerOnState":3,"LedState":1,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0,"InfoRetain":0,"StateRetain":0,"StatusRetain":0}}
12:04:03.045 MQT: stat/tasmota_482438/STATUS1 = {"StatusPRM":{"Baudrate":115200,"SerialConfig":"8N1","GroupTopic":"tasmotas","OtaUrl":"http://ota.tasmota.com/tasmota32/release/tasmota32c6.bin","RestartReason":"Software reset CPU","Uptime":"0T01:10:58","StartupUTC":"2024-08-02T09:53:05","Sleep":50,"CfgHolder":4617,"BootCount":6,"BCResetTime":"2024-08-02T10:44:32","SaveCount":17}}
12:04:03.054 MQT: stat/tasmota_482438/STATUS2 = {"StatusFWR":{"Version":"14.1.0.4(010ca34-tasmota32)","BuildDateTime":"2024-08-01T20:43:47","Core":"3_0_2","SDK":"5.1.4.240708","CpuFrequency":160,"Hardware":"ESP32-C6FH4 v0.0","CR":"403/699"}}
12:04:03.062 MQT: stat/tasmota_482438/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":4,"MqttLog":0,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["****",""],"TelePeriod":300,"Resolution":"558180C0","SetOption":["00008009","2805C80001000600003C5A0A192800000000","00000080","00006000","00004000","00000020"]}}
12:04:03.077 MQT: stat/tasmota_482438/STATUS4 = {"StatusMEM":{"ProgramSize":2012,"Free":867,"Heap":254,"StackLowMark":3,"PsrMax":0,"PsrFree":0,"ProgramFlashSize":4096,"FlashSize":4096,"FlashChipId":"164020","FlashFrequency":80,"FlashMode":"QIO","Features":["0809","9F9AD7DF","0015A001","B7F7BFCF","05DA9BC4","E0360DC7","480840D2","20200000","D4BC482D","810A80B1","00000014"],"Drivers":"1,2,!3,!4,!5,7,!8,9,10,11,12,!14,!16,!17,!20,!21,!24,26,!27,29,!34,!35,38,50,52,!59,!60,62,!63,!66,!67,!68,!73,82,!86,!87,!88,!121","Sensors":"1,2,3,5,6,7,8,9,10,11,12,13,14,15,17,18,19,20,21,22,26,31,34,37,39,40,42,43,45,51,52,55,56,58,59,64,66,67,74,85,92,95,98,103,105,109,127","I2CDriver":"7,8,9,10,11,12,13,14,15,17,18,20,24,29,31,36,41,42,44,46,48,58,62,65,69,76,77,82"}}
12:04:03.088 MQT: stat/tasmota_482438/STATUS5 = {"StatusNET":{"Hostname":"tasmota-482438-7752","IPAddress":"192.168.1.105","Gateway":"192.168.1.254","Subnetmask":"255.255.255.0","DNSServer1":"192.168.1.254","DNSServer2":"9.9.9.9","Mac":"40:4C:CA:48:24:38","IP6Global":"2a01:e0a:2b3:3990:424c:caff:fe48:2438","IP6Local":"fe80::424c:caff:fe48:2438%st1","Ethernet":{"Hostname":"","IPAddress":"0.0.0.0","Gateway":"0.0.0.0","Subnetmask":"0.0.0.0","DNSServer1":"192.168.1.254","DNSServer2":"9.9.9.9","Mac":"00:00:00:00:00:00","IP6Global":"","IP6Local":""},"Webserver":2,"HTTP_API":1,"WifiConfig":4,"WifiPower":16.0}}
12:04:03.096 BRY: GC from 33728 to 25957 bytes, objects freed 86/312 (in 1 ms) - slots from 492/593 to 281/532
12:04:03.101 MQT: stat/tasmota_482438/STATUS6 = {"StatusMQT":{"MqttHost":"homeassistant.local","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_482438","MqttUser":"lboue","MqttCount":1,"MAX_PACKET_SIZE":1200,"KEEPALIVE":30,"SOCKET_TIMEOUT":4}}
12:04:03.110 MQT: stat/tasmota_482438/STATUS7 = {"StatusTIM":{"UTC":"2024-08-02T11:04:03Z","Local":"2024-08-02T12:04:03","StartDST":"2024-03-31T02:00:00","EndDST":"2024-10-27T03:00:00","Timezone":"+01:00","Sunrise":"05:25","Sunset":"20:26"}}
12:04:03.118 MQT: stat/tasmota_482438/STATUS10 = {"StatusSNS":{"Time":"2024-08-02T12:04:03"}}
12:04:03.125 BRY: GC from 29070 to 23497 bytes, objects freed 50/259 (in 1 ms) - slots from 382/532 to 233/532
12:04:03.129 MQT: stat/tasmota_482438/STATUS11 = {"StatusSTS":{"Time":"2024-08-02T12:04:03","Uptime":"0T01:10:58","UptimeSec":4258,"Heap":255,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Berry":{"HeapUsed":22,"Objects":259},"Wifi":{"AP":1,"SSId":"****","BSSId":"C0:8A:DE:22:C5:B8","Channel":4,"Mode":"HT20","RSSI":100,"Signal":-39,"LinkCount":1,"Downtime":"0T00:00:05"}}}

```
- [x] Set `weblog` to 4 and then, when you experience your issue, provide the output of the Console log:
```lua
  Console output here:
12:03:35.385 HTP: Configuration
12:03:38.284 BRY: GC from 34294 to 25322 bytes, objects freed 133/300 (in 2 ms) - slots from 487/547 to 276/532
12:03:38.288 BRY: GC from 35758 to 25841 bytes, objects freed 69/303 (in 1 ms) - slots from 323/532 to 277/532
12:03:38.291 BRY: GC from 36083 to 26038 bytes, objects freed 40/303 (in 1 ms) - slots from 296/532 to 277/532
12:03:38.294 BRY: GC from 36289 to 25751 bytes, objects freed 32/301 (in 1 ms) - slots from 292/532 to 276/532
12:03:38.309 BRY: GC from 36328 to 24502 bytes, objects freed 48/296 (in 1 ms) - slots from 313/532 to 272/532
12:03:39.965 BRY: Exception> 'attribute_error' - the 'Matter_Device' object has no attribute 'start_root_basic_commissioning'

```

### TO REPRODUCE

1. Commissioning the Matter device with iOS Fabric
2. Go to Matter section
3. Check "commissioning open" box to allow commissioning the Matter device with Home Assistant.
4. Click "Save" button

### EXPECTED BEHAVIOUR
Open Matter commissioning

### SCREENSHOTS
image

image

image

### ADDITIONAL CONTEXT
_Add any other context about the problem here._

**(Please, remember to close the issue when the problem has been addressed)**

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Fix bug introduced in #21870

**Related issue (if applicable):** fixes #21890

## Checklist:
  - [x] The pull request is done against the latest development branch
  - [x] Only relevant files were touched
  - [x] Only one feature/fix was added per PR and the code change compiles without warnings
  - [ ] The code change is tested and works with Tasmota core ESP8266 V.2.7.7
  - [x] The code change is tested and works with Tasmota core ESP32 V.3.0.2
  - [x] I accept the [CLA](https://github.com/arendst/Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

_NOTE: The code change must pass CI tests. **Your PR cannot be merged unless tests pass**_

### CODE REVIEW

**Comment by lboue** [comment]
@s-hadinger Thanks
