### PR TITLE
Refactored TLS based on BearSSL - cleaned PR

### PR DESCRIPTION
**Pull request by s-hadinger**
## Description:

Extending the work started with AWS IoT, replacing the old AxTLS with BearSSL. Main benefit is a lower memory consumption (7.4k). This is a cleaned up version of PR #5931.

Warning, potential breaking change:

 - Core 2.3.0 not supported, TLS works only on Core 2.4.2 and 2.5.2
 - Single cipher supported: ECDHE_RSA_WITH_AES_128_GCM_SHA256 - whihch is quite common and natively supported by Mosquitto
 - Fingerprint validation is done against Public Key and not Certificate. If you are using letsencrypt, it's better since you won't need to change the fingerprint after certificate renewal.

After installing this version, you are strongly advised to do the following to enable auto-learning of the fingerprint.

```
MqttFingerprint1 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
```

You can also disable completely fingerprint validation with: (this is only acceptable if you are using an MQTT server on your local network)

```
MqttFingerprint1 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
```

**Related issue (if applicable):

## Checklist:
  - [x] The pull request is done against the latest dev branch
  - [x] Only relevant files were touched (Also remember to update _changelog.ino_ file)
  - [x] Only one feature/fix was added per PR.
  - [x] The code change is tested and works.
  - [x] The code change pass travis tests. **Your PR cannot be merged unless tests pass**
  - [x] I accept the [CLA](https://github.com/arendst/Sonoff-Tasmota/blob/development/CONTRIBUTING.md#contributor-license-agreement-cla).

### CODE REVIEW

**Comment by s-hadinger** [comment]
@arendst I finished my work on TLS replacement of BearSSL instead of AxTLS. I finally added CA validation including both Letsencrypt and AWS certification authorities. It consume a little more memory but still reasonable. I had it running for more than 16 hours and it seems stable.

It works on Core 2.4.2 and 2.5.2.

Full detail of memory usage here: https://github.com/arendst/Sonoff-Tasmota/wiki/AWS-IoT#memory-usage

Also, connection times here: https://github.com/arendst/Sonoff-Tasmota/wiki/AWS-IoT#connection-time

If you are ok, you can consider merging.

**Comment by arendst** [comment]
Will do. Shouldn't mdns be enabled for the non-tls defaults in my_user_config.h?

**Comment by s-hadinger** [comment]
Yes you're right, it seems one of my config got to the PR. Let ma change this.

**Comment by arendst** [comment]
Stephan,

the current setup using a bearssl include folder, libbearssl folder and platformio linker updates makes Tasmota compilation using Arduino IDE impossible without user hacks.

I did add a test for USE_MQTT_TLS in WifiClientSecureLightBearSSL.cpp to make Arduino compile again but it will be unable to compile for TLS.

Do you see a possibility to add the bearrssl library as a source library in the lib folder? This way Arduino IDE can also be persuaded to compile again.

Thx in advance, Theo.

**Comment by s-hadinger** [comment]
This was my original plan but it failed up to now.

First I struggled to force platformio to compile the module. Since all includes were referring to *.h files in Arduino, it would not detect the dependency on bearssl in the lib/ folder. I added an empty file and force a fake include to trigger the dependency manager to force the compile. Maybe there's a better way but I couldn't find it.

Unfortunately when compiling it miserably crashed afterwards. I tweaked the compile options but with no success.

I prioritized a working version first, and I have another PR on the works optimizing bearssl, that saves 8.5k of code for AWS IoT and 20k of code for Letsencrypt.

I will then work on putting bearssl in the lib/ folder. There's no reason why it shouldn't work...

**Comment by arendst** [comment]
Take your time.

**Comment by s-hadinger** [comment]
It was harder than I thought, especially with regards to performance.

Bearssl is now an Arduino lib and it works fine in Platformio. I hope it's ok on Arduino IDE.

If you want to try, it's on this branch: https://github.com/s-hadinger/Sonoff-Tasmota/commits/bearssl_local

It's too early to merge, I need to do some extra cleaning. I will try to find time to install Arduino IDE locally.

**Comment by arendst** [comment]
Thx.

Did some tests with your branch on platformio:

- As the library now will be compiled I removed the line ``-Llib_bearssl -lbearssl`` from platformio
- core 2.4.2 compile with or without using TLS fails with pgmspace.h error.
- core 2.5.2 compile with or without TLS and AWS works fine.

As I do not have an Arduino IDE with core 2.5.2 yet I couldn't test it there.

LOOKS PROMISSING!

What do you mean by performance issue? If it's more compile time I see it as no problem at all.

**Comment by s-hadinger** [comment]
I pushed some additional commits:

- removed `-Llib_bearssl -lbearssl`
- added back bearssl includes in `include` to avoid a conflict with the bearssl headers in 2.4.2
- added its own private version of `pgmspace.h` to bearssl to avoid conflict with 2.4.2

I tried on Arduino IDE 2.5.2 and it compiles well with AWS IoT and TLS.

Still same branch: https://github.com/s-hadinger/Sonoff-Tasmota/commits/bearssl_local

**Comment by s-hadinger** [comment]
As for performance issue, I saw a significant drop in speed from libbearssl.a comiled in stand-alone compared to compile with Tasmota. I tweaked all kinds of compile options with no luck. I finally re-wrote the faulty inner loop, and it runs even faster now: https://github.com/earlephilhower/bearssl-esp8266/pull/13

**Comment by arendst** [comment]
Great!

- Just tested it too with Arduino IDE 1.8.9 and core 2.5.2 enabling TLS and AWS and it compiles just fine.
- Alas does it fail compile on IDE 1.8.9 and core 2.4.2 enabling TLS and AWS:
```
In file included from sketch\WiFiClientSecureLightBearSSL.cpp:41:0:
sketch\WiFiClientSecureLightBearSSL.h: In member function 'int BearSSL::WiFiClientSecure_light::getMFLNStatus()':
WiFiClientSecureLightBearSSL.h:84:67: error: 'br_ssl_engine_get_mfln_negotiated' was not declared in this scope
       return connected() && br_ssl_engine_get_mfln_negotiated(_eng);
                                                                   ^
In file included from C:\Users\Theo\Documents\VisualStudio\arduino-esp8266\Tasmota\Development\Sonoff-Tasmota-bearssl-20190617\sonoff\xdrv_02_mqtt.ino:23:0:
sketch\WiFiClientSecureLightBearSSL.h: In member function 'int BearSSL::WiFiClientSecure_light::getMFLNStatus()':
WiFiClientSecureLightBearSSL.h:84:67: error: 'br_ssl_engine_get_mfln_negotiated' was not declared in this scope
       return connected() && br_ssl_engine_get_mfln_negotiated(_eng);
                                                                   ^
exit status 1
'br_ssl_engine_get_mfln_negotiated' was not declared in this scope
```
- Arduino IDE and core 2.4.2 without TLS compiles just fine.

**Comment by s-hadinger** [comment]
Yes, this is due to a conflict with the BearSSL headers in 2.4.2. Unfortunately I can't find a way to have the includes of libs take priority over the includes of Arduino core. With Platformio you can put them in the `include/` folder, I can't find an equivalent with Arduino IDE.

I'll try a more radical approach and rename all bearssl headers to disambiguate.

**Comment by s-hadinger** [comment]
@arendst It compiles fine now on Arduino, both 2.4.2 and 2.5.2.
